# ASSIGNMENT 2

<h3>Group Member :</h3>  

<table style="width: 400px; margin-left:0px">
  <tr>
    <th style="text-align:center">Name</th>
    <th style="text-align:center">Matric No</th>
  </tr>
  <tr>
    <td style="text-align:center">GOO YE JUI</td>
    <td style="text-align:center">A20EC0191</td>
  </tr>
  <tr>
    <td style="text-align:center">HONG PEI GEOK</td>
    <td style="text-align:center">A20EC0044</td>
  </tr>
  <tr>
    <td style="text-align:center">YONG ZHI YAN</td>
    <td style="text-align:center">A20EC0172</td>
  </tr>
       
</table>

### NumPy

In [1]:
import numpy as np

In [2]:
# Task 1
path = "Attendance_RAW.txt"
lines = [x.rstrip() for x in open(path)]

attend = np.array(lines, dtype=int)
attend

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0,
       0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,
       1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1])

In [3]:
# Task 2
attend = attend.reshape(14,15).T
attend

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0],
       [1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1],
       [1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1],
       [1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1],
       [1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0],
       [1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0],
       [1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1],
       [1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1],
       [0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1]])

In [4]:
# Task 3
def average(record):
    avg = record.mean(axis=0).round(2)
    return avg
    
attend_per_day = average(attend)
attend_per_day

array([0.93, 0.93, 0.67, 0.67, 0.73, 0.73, 0.73, 0.6 , 0.73, 0.67, 1.  ,
       0.67, 0.8 , 0.67])

### Pandas

In [5]:
import pandas as pd

In [6]:
# Task 1
emp_detail = pd.read_csv("emp_detail.csv")

In [7]:
# Task 2
emp_detail.head()

Name Department
0      ALI    FINANCE
1    AHMAD   STAFFING
2    CHONG    FINANCE
3   DARREN   STAFFING
4  JASMINE   STAFFING

In [8]:
# Task 3a
attendance = pd.DataFrame(attend)
attendance

0   1   2   3   4   5   6   7   8   9   10  11  12  13
0    1   1   1   1   1   1   1   1   1   1   1   1   1   1
1    1   1   1   0   1   1   1   1   1   1   1   1   1   1
2    1   1   1   1   1   1   0   1   0   0   1   0   0   0
3    1   1   1   1   1   0   1   0   1   1   1   1   0   1
4    1   1   0   1   0   1   1   0   1   0   1   1   1   1
5    1   1   1   1   0   1   0   1   1   0   1   0   1   1
6    1   1   0   0   0   1   1   0   0   0   1   0   1   0
7    1   1   0   1   0   0   1   0   1   0   1   0   1   0
8    1   1   1   1   1   1   0   1   0   1   1   0   1   0
9    1   0   1   1   1   1   0   1   1   1   1   1   1   1
10   1   1   0   1   1   1   1   1   0   1   1   1   1   0
11   1   1   1   1   1   1   1   1   1   1   1   1   1   1
12   1   1   1   0   1   0   1   0   1   1   1   1   1   1
13   1   1   0   0   1   0   1   1   1   1   1   1   1   1
14   0   1   1   0   1   1   1   0   1   1   1   1   0   1

In [9]:
# Task 3b
emp_attendance = pd.concat([emp_detail, attendance], axis = 1)
emp_attendance

Name Department  0  1  2  3  4  5  6  7  8  9  10  11  12  13
0       ALI    FINANCE  1  1  1  1  1  1  1  1  1  1   1   1   1   1
1     AHMAD   STAFFING  1  1  1  0  1  1  1  1  1  1   1   1   1   1
2     CHONG    FINANCE  1  1  1  1  1  1  0  1  0  0   1   0   0   0
3    DARREN   STAFFING  1  1  1  1  1  0  1  0  1  1   1   1   0   1
4   JASMINE   STAFFING  1  1  0  1  0  1  1  0  1  0   1   1   1   1
5    JOSHUA   STAFFING  1  1  1  1  0  1  0  1  1  0   1   0   1   1
6     KELLY    FINANCE  1  1  0  0  0  1  1  0  0  0   1   0   1   0
7       LIM    FINANCE  1  1  0  1  0  0  1  0  1  0   1   0   1   0
8   NATASHA    FINANCE  1  1  1  1  1  1  0  1  0  1   1   0   1   0
9      OMAR   STAFFING  1  0  1  1  1  1  0  1  1  1   1   1   1   1
10   PATRIC   STAFFING  1  1  0  1  1  1  1  1  0  1   1   1   1   0
11     ROSE   STAFFING  1  1  1  1  1  1  1  1  1  1   1   1   1   1
12    SATYA   STAFFING  1  1  1  0  1  0  1  0  1  1   1   1   1   1
13    TARIQ   STAFFING  1  1  0  0  1  0  1  1  1  1   1   1   1   1
14    USMAN   STAFFING  0  1  1  0  1  1  1  0  1  1   1   1   0   1

In [10]:
# Task 4
emp_attendance['total'] = attendance.sum(axis = 1)
emp_attendance

Name Department  0  1  2  3  4  5  6  7  8  9  10  11  12  13  total
0       ALI    FINANCE  1  1  1  1  1  1  1  1  1  1   1   1   1   1     14
1     AHMAD   STAFFING  1  1  1  0  1  1  1  1  1  1   1   1   1   1     13
2     CHONG    FINANCE  1  1  1  1  1  1  0  1  0  0   1   0   0   0      8
3    DARREN   STAFFING  1  1  1  1  1  0  1  0  1  1   1   1   0   1     11
4   JASMINE   STAFFING  1  1  0  1  0  1  1  0  1  0   1   1   1   1     10
5    JOSHUA   STAFFING  1  1  1  1  0  1  0  1  1  0   1   0   1   1     10
6     KELLY    FINANCE  1  1  0  0  0  1  1  0  0  0   1   0   1   0      6
7       LIM    FINANCE  1  1  0  1  0  0  1  0  1  0   1   0   1   0      7
8   NATASHA    FINANCE  1  1  1  1  1  1  0  1  0  1   1   0   1   0     10
9      OMAR   STAFFING  1  0  1  1  1  1  0  1  1  1   1   1   1   1     12
10   PATRIC   STAFFING  1  1  0  1  1  1  1  1  0  1   1   1   1   0     11
11     ROSE   STAFFING  1  1  1  1  1  1  1  1  1  1   1   1   1   1     14
12    SATYA   STAFFING  1  1  1  0  1  0  1  0  1  1   1   1   1   1     11
13    TARIQ   STAFFING  1  1  0  0  1  0  1  1  1  1   1   1   1   1     11
14    USMAN   STAFFING  0  1  1  0  1  1  1  0  1  1   1   1   0   1     10

In [11]:
# Task 5
emp_attendance['rate'] = round((emp_attendance['total']/14)*100, 2)
emp_attendance

Name Department  0  1  2  3  4  5  6  7  8  9  10  11  12  13  total  \
0       ALI    FINANCE  1  1  1  1  1  1  1  1  1  1   1   1   1   1     14   
1     AHMAD   STAFFING  1  1  1  0  1  1  1  1  1  1   1   1   1   1     13   
2     CHONG    FINANCE  1  1  1  1  1  1  0  1  0  0   1   0   0   0      8   
3    DARREN   STAFFING  1  1  1  1  1  0  1  0  1  1   1   1   0   1     11   
4   JASMINE   STAFFING  1  1  0  1  0  1  1  0  1  0   1   1   1   1     10   
5    JOSHUA   STAFFING  1  1  1  1  0  1  0  1  1  0   1   0   1   1     10   
6     KELLY    FINANCE  1  1  0  0  0  1  1  0  0  0   1   0   1   0      6   
7       LIM    FINANCE  1  1  0  1  0  0  1  0  1  0   1   0   1   0      7   
8   NATASHA    FINANCE  1  1  1  1  1  1  0  1  0  1   1   0   1   0     10   
9      OMAR   STAFFING  1  0  1  1  1  1  0  1  1  1   1   1   1   1     12   
10   PATRIC   STAFFING  1  1  0  1  1  1  1  1  0  1   1   1   1   0     11   
11     ROSE   STAFFING  1  1  1  1  1  1  1  1  1  1   1   1   1   1     14   
12    SATYA   STAFFING  1  1  1  0  1  0  1  0  1  1   1   1   1   1     11   
13    TARIQ   STAFFING  1  1  0  0  1  0  1  1  1  1   1   1   1   1     11   
14    USMAN   STAFFING  0  1  1  0  1  1  1  0  1  1   1   1   0   1     10   

      rate  
0   100.00  
1    92.86  
2    57.14  
3    78.57  
4    71.43  
5    71.43  
6    42.86  
7    50.00  
8    71.43  
9    85.71  
10   78.57  
11  100.00  
12   78.57  
13   78.57  
14   71.43

In [12]:
# Task 6
emp_attendance['status'] = np.where(emp_attendance['rate']>90, "Good", np.where(emp_attendance['rate']>60, "Moderate", "Bad"))
emp_attendance

Name Department  0  1  2  3  4  5  6  7  8  9  10  11  12  13  total  \
0       ALI    FINANCE  1  1  1  1  1  1  1  1  1  1   1   1   1   1     14   
1     AHMAD   STAFFING  1  1  1  0  1  1  1  1  1  1   1   1   1   1     13   
2     CHONG    FINANCE  1  1  1  1  1  1  0  1  0  0   1   0   0   0      8   
3    DARREN   STAFFING  1  1  1  1  1  0  1  0  1  1   1   1   0   1     11   
4   JASMINE   STAFFING  1  1  0  1  0  1  1  0  1  0   1   1   1   1     10   
5    JOSHUA   STAFFING  1  1  1  1  0  1  0  1  1  0   1   0   1   1     10   
6     KELLY    FINANCE  1  1  0  0  0  1  1  0  0  0   1   0   1   0      6   
7       LIM    FINANCE  1  1  0  1  0  0  1  0  1  0   1   0   1   0      7   
8   NATASHA    FINANCE  1  1  1  1  1  1  0  1  0  1   1   0   1   0     10   
9      OMAR   STAFFING  1  0  1  1  1  1  0  1  1  1   1   1   1   1     12   
10   PATRIC   STAFFING  1  1  0  1  1  1  1  1  0  1   1   1   1   0     11   
11     ROSE   STAFFING  1  1  1  1  1  1  1  1  1  1   1   1   1   1     14   
12    SATYA   STAFFING  1  1  1  0  1  0  1  0  1  1   1   1   1   1     11   
13    TARIQ   STAFFING  1  1  0  0  1  0  1  1  1  1   1   1   1   1     11   
14    USMAN   STAFFING  0  1  1  0  1  1  1  0  1  1   1   1   0   1     10   

      rate    status  
0   100.00      Good  
1    92.86      Good  
2    57.14       Bad  
3    78.57  Moderate  
4    71.43  Moderate  
5    71.43  Moderate  
6    42.86       Bad  
7    50.00       Bad  
8    71.43  Moderate  
9    85.71  Moderate  
10   78.57  Moderate  
11  100.00      Good  
12   78.57  Moderate  
13   78.57  Moderate  
14   71.43  Moderate

In [13]:
# Task 7
def department_avg(record):
    avg = record.groupby('Department').mean()
    return avg['total']
    
attend_by_depart = department_avg(emp_attendance)
attend_by_depart

Department
FINANCE      9.0
STAFFING    11.3
Name: total, dtype: float64